// Atlas Configuration for GORM Schema
// This file configures Atlas to generate migrations from GORM entities
// Documentation: https://atlasgo.io/guides/orms/gorm
//
// NOTE: Database URL is auto-generated from existing ENV variables
// Set via Makefile using cmd/atlas-dsn helper
// Uses: DB_USER, DB_PASS, DB_URL, DB_NAME, DB_TYPE

// Database URL variable (set by Makefile)
variable "db_url" {
  type    = string
  default = getenv("ATLAS_DB_URL")
}

// Data source configuration - GORM models
data "external_schema" "gorm" {
  program = [
    "go",
    "run",
    "-mod=mod",
    "./cmd/atlas"
  ]
}

// Environment definitions
env "local" {
  src = data.external_schema.gorm.url
  
  // Local development database URL (auto-generated by Makefile)
  dev = var.db_url
  url = var.db_url
  
  // Migration directory
  migration {
    dir = "file://migrations"
  }
  
  // Format migrations
  format {
    migrate {
      diff = "{{ sql . \"  \" }}"
    }
  }
}

env "dev" {
  src = data.external_schema.gorm.url
  
  // Development database URL (auto-generated from ENV by Makefile)
  dev = var.db_url
  url = var.db_url
  
  // Migration directory
  migration {
    dir = "file://migrations"
  }
  
  // Diff policy - compare against dev database
  diff {
    skip {
      // Skip audit log changes if not enabled
      drop_schema = true
    }
  }
}

env "prod" {
  src = data.external_schema.gorm.url
  
  // Production database URL (auto-generated from ENV by Makefile)
  url = var.db_url
  
  // Migration directory
  migration {
    dir = "file://migrations"
  }
  
  // Apply policy for production
  diff {
    skip {
      drop_schema = true
      drop_table  = true
    }
  }
  
  // Require approval for production
  lint {
    destructive {
      error = true
    }
  }
}
